***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Loading genomes from a list
Nevermind! Ill try loading as a genome now
Traceback (most recent call last):
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/lib/python3.10/site-packages/drep/d_workflows.py", line 29, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/lib/python3.10/site-packages/drep/d_filter.py", line 63, in d_filter_wrapper
    bdb = drep.d_cluster.utils.load_genomes(kwargs['genomes'])
  File "/shared/home/asandri/miniforge3/envs/mahabio_env/lib/python3.10/site-packages/drep/d_cluster/utils.py", line 605, in load_genomes
    assert os.path.isfile(genome), "{0} is not a file".format(genome)
AssertionError: /shared/home/asandri/MAHABIO_analysis/results/binning/stats/16S_detection/semibin/C_contigs_more_than_300bp/*.fasta is not a file
